---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: application-repo
spec:
  type: git
  params:
    - name: url
      value: https://github.com/drewdouglass1/mod-resorts-demo.git
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: application-image
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/default/modresortswar:latest
